#!/usr/bin/with-contenv bash

if [ "${UNBOUND_ENABLED}" -ne 1 ]; then
    s6-svc -d .
    exit 0
fi

cmd="unbound -d -p -c ${UNBOUND_CONFIG}"
echo "*** executing => $cmd"
exec s6-notifyoncheck -d -n 0 -s 1000 \
    $cmd
