#!/usr/bin/with-contenv bash

if [ "${STUBBY_ENABLED}" -ne 1 ]; then
    s6-svc -d .
    exit 0
fi

IFS=" " read -r -a stubby_opts <<< "$STUBBY_OPTS"

cmd="stubby -C ${STUBBY_CONFIG} ${stubby_opts[@]}"
echo "*** executing => $cmd"
exec s6-notifyoncheck -d -n 0 -s 2000 \
    s6-setuidgid abc $cmd
