#!/usr/bin/with-contenv bash

if [ "${STUBBY_ENABLED}" -ne 1 ]; then
    s6-svc -d .
    exit 0
fi

cmd="stubby -C ${STUBBY_CONFIG} $STUBBY_OPTS"
echo "*** executing => $cmd"
exec s6-notifyoncheck -d -n 0 -s 2000 \
    s6-setuidgid abc $cmd
