#!/usr/bin/with-contenv bash

if [ "${STUBBY_ENABLED}" -eq 1 ]; then
    s6-svwait -U /var/run/service/stubby
fi

cmd="unbound -d -p -c ${UNBOUND_CONFIG}"
echo "*** executing => $cmd"
exec s6-notifyoncheck -d -n 0 -s 1000 \
    $cmd
