#!/usr/bin/with-contenv bash

if [ -z "${TUNNEL_TOKEN}" ]; then
    s6-svc -d .
    exit 0
fi

if [ "${UNBOUND_ENABLED}" -eq 1 ]; then
    s6-svwait -U /var/run/service/unbound
fi

s6-svwait -u /var/run/service/adguardhome

cmd="cloudflared --no-autoupdate tunnel run"
echo "*** executing => $cmd"
exec s6-setuidgid abc $cmd
