name: buildx

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
  schedule:
    - cron: "45 */6 * * *"

env:
  IMAGE_NAME: ghcr.io/by275/adguardhome
  X_SKIP: "true"
  APP_VER: unknown

jobs:
  buildx:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        build: [latest, beta]
    steps:
      -
        name: Check if buildx required
        run: |
          if [ $GITHUB_EVENT_NAME != "schedule" ]; then
            echo "X_SKIP=false" >> $GITHUB_ENV
            exit 0
          fi
          docker run --rm --entrypoint=cat adguard/adguardhome:${{ matrix.build }} \
            /opt/adguardhome/AdGuardHome > bin1
          docker run --rm --entrypoint=cat ${{ env.IMAGE_NAME }}:${{ matrix.build }} \
            /usr/local/bin/AdGuardHome > bin2
          if ! cmp -s bin1 bin2 ; then echo "X_SKIP=false" >> $GITHUB_ENV ; fi
      -
        name: Checkout
        if: env.X_SKIP == 'false'
        uses: actions/checkout@v7
      -
        name: Set up QEMU
        if: env.X_SKIP == 'false'
        uses: docker/setup-qemu-action@v4
      -
        name: Set up Buildx
        if: env.X_SKIP == 'false'
        uses: docker/setup-buildx-action@v4
      -
        name: Build Unbound (amd64)
        if: env.X_SKIP == 'false'
        uses: docker/build-push-action@v7
        with:
          context: .
          file: unbound.dockerfile
          build-args: |
            ARCH=amd64
          outputs: type=local,dest=./unbound/amd64
          cache-from: type=gha,scope=adguardhome-unbound-${{ matrix.build }}-amd64
          cache-to: type=gha,mode=max,scope=adguardhome-unbound-${{ matrix.build }}-amd64,ignore-error=true
          pull: true
          no-cache: ${{ github.event_name == 'schedule' }}
      -
        name: Build Unbound (arm64)
        if: env.X_SKIP == 'false'
        uses: docker/build-push-action@v7
        with:
          context: .
          file: unbound.dockerfile
          build-args: |
            ARCH=arm64
          outputs: type=local,dest=./unbound/arm64
          cache-from: type=gha,scope=adguardhome-unbound-${{ matrix.build }}-arm64
          cache-to: type=gha,mode=max,scope=adguardhome-unbound-${{ matrix.build }}-arm64,ignore-error=true
          pull: true
          no-cache: ${{ github.event_name == 'schedule' }}
      -
        name: Initial Buildx
        if: env.X_SKIP == 'false'
        uses: docker/build-push-action@v7
        with:
          context: .
          file: Dockerfile
          tags: ${{ env.IMAGE_NAME }}:testing
          platforms: linux/amd64,linux/arm64
          build-args: |
            AGH_BUILD=${{ matrix.build }}
          cache-from: type=gha,scope=adguardhome-${{ matrix.build }}
          pull: true
          no-cache: ${{ github.event_name == 'schedule' }}
      -
        name: Load Built Image
        if: env.X_SKIP == 'false'
        uses: docker/build-push-action@v7
        with:
          context: .
          file: Dockerfile
          tags: ${{ env.IMAGE_NAME }}:testing
          platforms: linux/amd64
          build-args: |
            AGH_BUILD=${{ matrix.build }}
          load: true
      -
        name: Get Variables
        if: env.X_SKIP == 'false'
        run: |
          CID=$(docker run -d ${{ env.IMAGE_NAME }}:testing)
          VER=$(docker exec $CID AdGuardHome --version | awk '{print $NF}' | cut -d'+' -f1)
          docker rm -f $CID
          echo "APP_VER=$VER" >> $GITHUB_ENV
      -
        name: Login to ghcr.io
        if: env.X_SKIP == 'false'
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Buildx and Push
        if: env.X_SKIP == 'false'
        uses: docker/build-push-action@v7
        with:
          context: .
          file: Dockerfile
          tags: |
            ${{ env.IMAGE_NAME }}:${{ matrix.build }}
            ${{ env.IMAGE_NAME }}:${{ env.APP_VER }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            AGH_BUILD=${{ matrix.build }}
          cache-to: type=gha,mode=max,scope=adguardhome-${{ matrix.build }},ignore-error=true
          push: true
      -
        name: Notification
        uses: sarisia/actions-status-discord@v1
        if: env.X_SKIP == 'false' && always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          description: |
            ${{ env.IMAGE_NAME }}:${{ matrix.build }}
            ${{ env.IMAGE_NAME }}:${{ env.APP_VER }}
