#!/usr/bin/with-contenv bash

if [ "${UNBOUND_ENABLED}" -ne 1 ]; then
    rm -f /var/run/service/unbound/notification-fd
    exit 0
fi

mkdir -p /config/unbound.conf.d

for srcfile in /defaults/unbound.conf.d/*; do
    trgfile="/config/unbound.conf.d/$(basename "$srcfile")"
    if [ ! -f "$trgfile" ]; then
        cp "$srcfile" "$trgfile"
    fi
done

rm -f "${UNBOUND_CONFIG}"
envsubst < "/defaults/unbound.conf" > "${UNBOUND_CONFIG}"

if [ "${STUBBY_ENABLED}" -eq 1 ]; then
    echo "    forward-addr: 127.0.0.1@${STUBBY_PORT}" >> "${UNBOUND_CONFIG}"
else
    echo "*** unbound upstreams: $UNBOUND_UPSTREAMS"
    echo "    forward-tls-upstream: yes" >> "${UNBOUND_CONFIG}"
    IFS=" " read -r -a upstreams <<< "$UNBOUND_UPSTREAMS"
    for upstream in "${upstreams[@]}"; do
        echo "    forward-addr: $upstream" >> "${UNBOUND_CONFIG}"
    done
fi

# root.hints
curl -o /usr/local/etc/unbound/root.hints \
    -fsS https://www.internic.net/domain/named.root

# trust anchor
unbound-anchor -a /usr/local/etc/unbound/root.key

# permissions
chown -R abc:abc \
    /usr/local/etc/unbound \
    /config/unbound.conf.d

echo "*** unbound $(unbound -V | head -1 | cut -d' ' -f2) ready!"
