#!/usr/bin/with-contenv bash

if [ "${AGH_ENABLED}" -ne 1 ]; then
    exit 0
fi

mkdir -p /config

# permissions
chown -R abc:abc \
    /config

echo "*** AdGuardHome $(AdGuardHome --version | awk '{print $NF}') ready!"
